version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - cobertura:cobertura
      name: Send to CodeCov
      command: bash <(curl -s https://codecov.io/bash)
